/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DaoDespesa;
import Controller.DaoInquilino;
import Model.Despesa;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class TelaDespesa extends javax.swing.JFrame {

    /**
     * Creates new form TelaDespesa
     */
    public TelaDespesa() {
        initComponents();
        CarregarTabela();
        DesabilitarJbuttom();
        DesabilitarJTextField();
        LimparjTextField();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelCodDespesa = new javax.swing.JLabel();
        jLabelCodUnidade = new javax.swing.JLabel();
        jLabelVencimento = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldCodDespesa = new javax.swing.JTextField();
        jTextFieldCodUnidade = new javax.swing.JTextField();
        jTextFieldVencimento = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDespesa = new javax.swing.JTable();
        jPanelFiltros = new javax.swing.JPanel();
        jPanelFiltroUnidade = new javax.swing.JPanel();
        jLabelFiltroUnidade = new javax.swing.JLabel();
        jTextFieldFiltroUnidade = new javax.swing.JTextField();
        jButtonFiltrarUnidade = new javax.swing.JButton();
        jButtonFitroDespesasVencidas = new javax.swing.JButton();
        jButtonLimparFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Criação / Edição de Despesas"));

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/novo.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salvar.png"))); // NOI18N
        jButtonSalvar.setText("salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atualizar.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabelCodDespesa.setText("Cod Despesa");

        jLabelCodUnidade.setText("Cod Unidade");

        jLabelVencimento.setText("Vencimento");

        jLabelTipo.setText("Tipo");

        jLabelValor.setText("Valor");

        jLabelDescricao.setText("Descrição");

        jLabelStatus.setText("Status");

        jTextFieldCodDespesa.setText("jTextField1");

        jTextFieldCodUnidade.setText("jTextField2");

        jTextFieldVencimento.setText("jTextField3");

        jTextFieldTipo.setText("jTextField4");

        jTextFieldValor.setText("jTextField1");

        jTextFieldDescricao.setText("jTextField1");

        jTextFieldStatus.setText("jTextField1");

        jLabelInfo.setForeground(new java.awt.Color(255, 0, 102));
        jLabelInfo.setText("Selecione Registro na tabela abaixo para Edição");

        jTableDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Despesa", "Cod Unidade", "Descrição", "Tipo", "Valor", "Vencimento", "Status"
            }
        ));
        jTableDespesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDespesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDespesa);

        jPanelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jPanelFiltroUnidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar por Unidade"));

        jLabelFiltroUnidade.setText("Unidade");

        jTextFieldFiltroUnidade.setText("1");

        jButtonFiltrarUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/filtro.png"))); // NOI18N
        jButtonFiltrarUnidade.setText("Filtrar");
        jButtonFiltrarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarUnidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltroUnidadeLayout = new javax.swing.GroupLayout(jPanelFiltroUnidade);
        jPanelFiltroUnidade.setLayout(jPanelFiltroUnidadeLayout);
        jPanelFiltroUnidadeLayout.setHorizontalGroup(
            jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                .addGroup(jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                        .addComponent(jLabelFiltroUnidade)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jTextFieldFiltroUnidade))
                .addGap(18, 18, 18)
                .addComponent(jButtonFiltrarUnidade)
                .addContainerGap())
        );
        jPanelFiltroUnidadeLayout.setVerticalGroup(
            jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFiltrarUnidade)
                    .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                        .addComponent(jLabelFiltroUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFiltroUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFitroDespesasVencidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Despesas.png"))); // NOI18N
        jButtonFitroDespesasVencidas.setText("Despesas Vencidas");
        jButtonFitroDespesasVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFitroDespesasVencidasActionPerformed(evt);
            }
        });

        jButtonLimparFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limparFiltro.png"))); // NOI18N
        jButtonLimparFiltros.setText("Limpar Filtros");
        jButtonLimparFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFiltroUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonFitroDespesasVencidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLimparFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addComponent(jPanelFiltroUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFitroDespesasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimparFiltros)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBaseLayout.createSequentialGroup()
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelBaseLayout.createSequentialGroup()
                                            .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelCodDespesa, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldCodDespesa, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelCodUnidade)
                                                .addComponent(jTextFieldCodUnidade)))
                                        .addComponent(jTextFieldDescricao))
                                    .addComponent(jLabelDescricao))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVencimento)
                                    .addComponent(jTextFieldVencimento)
                                    .addComponent(jLabelStatus)
                                    .addComponent(jTextFieldStatus))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                                        .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldValor))
                                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonExcluir)
                                            .addComponent(jLabelTipo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabelInfo))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNovo)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonExcluir)
                            .addComponent(jButtonHome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodDespesa)
                            .addComponent(jLabelCodUnidade)
                            .addComponent(jLabelVencimento)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescricao)
                            .addComponent(jLabelStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelInfo))
                    .addComponent(jPanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        HabilitarJTextField();
        DesabilitarJbuttom();
        jButtonSalvar.setEnabled(true);
        LimparjTextField();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        Despesa despesas = new Despesa();
        DaoDespesa daoDespesas = new DaoDespesa();

        despesas.setCodUnidade(Integer.parseInt(jTextFieldCodUnidade.getText()));
        despesas.setDescricao(jTextFieldDescricao.getText()); 
        despesas.setTipo(jTextFieldTipo.getText()); 
        despesas.setValor(Double.parseDouble(jTextFieldValor.getText()));   
        try{
            despesas.setVencimento(Date.valueOf(jTextFieldVencimento.getText()));
        }catch(Exception e){            
            JOptionPane.showMessageDialog(null,"Dada Formado Invalido: "
                    + "Digitar no formado yyyy/MM/dd",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
            return;
        }
        despesas.setStatusPgto(Boolean.valueOf(jTextFieldStatus.getText()));

        daoDespesas.cadastrarDespesa(despesas);
        CarregarTabela();
        LimparjTextField();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        Despesa despesas =new Despesa();
        DaoDespesa daoDespesa =new DaoDespesa();
        Integer index = jTableDespesa.getSelectedRow();

        despesas =daoDespesa.listarDespesa().get(index);
        despesas.setCodUnidade(Integer.parseInt(jTextFieldCodUnidade.getText()));
        despesas.setDescricao(jTextFieldDescricao.getText()); 
        despesas.setTipo(jTextFieldTipo.getText()); 
        despesas.setValor(Double.parseDouble(jTextFieldValor.getText()));        
        despesas.setVencimento(Date.valueOf(jTextFieldVencimento.getText()));
        despesas.setStatusPgto(Boolean.valueOf(jTextFieldStatus.getText()));;

        daoDespesa.editarDespesa(despesas);
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        Despesa despesas =new Despesa();
        DaoDespesa daoDespesas = new DaoDespesa();
        Integer index = jTableDespesa.getSelectedRow();
        despesas = daoDespesas.listarDespesa().get(index);
        daoDespesas.removerDespesa(Integer.parseInt(jTextFieldCodDespesa.getText()));
        CarregarTabela();
        LimparjTextField();
        DesabilitarJTextField();
        DesabilitarJbuttom();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableDespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDespesaMouseClicked

        Despesa despesas = new Despesa();
        DaoDespesa daoDespesas =new DaoDespesa();
        Integer index = jTableDespesa.getSelectedRow();
        despesas= daoDespesas.listarDespesa().get(index);

        jTextFieldCodDespesa.setText(String.valueOf(despesas.getCodDespesa()));
        jTextFieldCodUnidade.setText(String.valueOf(despesas.getCodUnidade()));
        jTextFieldDescricao.setText(despesas.getDescricao());      
        jTextFieldTipo.setText(String.valueOf(despesas.getTipo())); 
        jTextFieldValor.setText(String.valueOf(despesas.getValor()));
        jTextFieldVencimento.setText(String.valueOf(despesas.getVencimento()));
        jTextFieldStatus.setText(String.valueOf(despesas.getStatusPgto()));

        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        HabilitarJTextField();
    }//GEN-LAST:event_jTableDespesaMouseClicked

    private void jButtonFiltrarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarUnidadeActionPerformed
        
        CarregarTabelaFiltroUnidade();   
    }//GEN-LAST:event_jButtonFiltrarUnidadeActionPerformed

    private void jButtonLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparFiltrosActionPerformed
      
        CarregarTabela();
    }//GEN-LAST:event_jButtonLimparFiltrosActionPerformed

    private void jButtonFitroDespesasVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFitroDespesasVencidasActionPerformed

        CarregarTabelaFiltroDespesaVencida();
    }//GEN-LAST:event_jButtonFitroDespesasVencidasActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed

        try {
            TelaPrincipal telaPrincipal = new TelaPrincipal();
            telaPrincipal.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        } 
        finally{
        dispose();
        }                
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void LimparjTextField(){
        jTextFieldCodDespesa.setText("");
        jTextFieldCodUnidade.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldTipo.setText("");
        jTextFieldValor.setText("");
        jTextFieldVencimento.setText("");
        jTextFieldStatus.setText("");      
    }    
    
    private void DesabilitarJbuttom(){
        jButtonEditar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(false);    
    }

    private void HabilitarJbuttom(){
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }       
    
    private void DesabilitarJTextField(){
        jTextFieldCodDespesa.setEnabled(false);
        jTextFieldCodUnidade.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldStatus.setEnabled(false);
        jTextFieldTipo.setEnabled(false);
        jTextFieldValor.setEnabled(false);
        jTextFieldVencimento.setEnabled(false);
      
        
        jLabelCodDespesa.setEnabled(false);
        jLabelCodUnidade.setEnabled(false);
        jLabelDescricao.setEnabled(false);
        jLabelStatus.setEnabled(false);
        jLabelTipo.setEnabled(false);
        jLabelValor.setEnabled(false);
        jLabelVencimento.setEnabled(false);        
    }
        
    private void HabilitarJTextField(){

        jTextFieldCodUnidade.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jTextFieldStatus.setEnabled(true);
        jTextFieldTipo.setEnabled(true);
        jTextFieldValor.setEnabled(true);
        jTextFieldVencimento.setEnabled(true);
      
        jLabelCodUnidade.setEnabled(true);
        jLabelDescricao.setEnabled(true);
        jLabelStatus.setEnabled(true);
        jLabelTipo.setEnabled(true);
        jLabelValor.setEnabled(true);
        jLabelVencimento.setEnabled(true);        
        
    }
    
    private void CarregarTabela(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableDespesa.getModel();
        tabela.setNumRows(0);
      
        DaoDespesa daoDespesas = new DaoDespesa();
        
        try {
            for(Despesa d: daoDespesas.listarDespesa()){
                tabela.addRow(new Object[]{
                    d.getCodDespesa(),
                    d.getCodUnidade(),                   
                    d.getDescricao(),
                    d.getTipo(),
                    d.getValor(),
                    d.getVencimento(),
                    d.getStatusPgto()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }        
    
    private void CarregarTabelaFiltroUnidade(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableDespesa.getModel();
        tabela.setNumRows(0);
      
        DaoDespesa daoDespesas = new DaoDespesa();
        
        try {
            for(Despesa d: daoDespesas.listarDespesaFiltroUnidade(Integer.parseInt(jTextFieldFiltroUnidade.getText()))){
                tabela.addRow(new Object[]{
                    d.getCodDespesa(),
                    d.getCodUnidade(),                   
                    d.getDescricao(),
                    d.getTipo(),
                    d.getValor(),
                    d.getVencimento(),
                    d.getStatusPgto()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }  
    
    private void CarregarTabelaFiltroDespesaVencida(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableDespesa.getModel();
        tabela.setNumRows(0);
      
        DaoDespesa daoDespesas = new DaoDespesa();
        
        try {
            for(Despesa d: daoDespesas.listarDespesaVencidada()){
                tabela.addRow(new Object[]{
                    d.getCodDespesa(),
                    d.getCodUnidade(),                   
                    d.getDescricao(),
                    d.getTipo(),
                    d.getValor(),
                    d.getVencimento(),
                    d.getStatusPgto()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFiltrarUnidade;
    private javax.swing.JButton jButtonFitroDespesasVencidas;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLimparFiltros;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCodDespesa;
    private javax.swing.JLabel jLabelCodUnidade;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelFiltroUnidade;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelVencimento;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelFiltroUnidade;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDespesa;
    private javax.swing.JTextField jTextFieldCodDespesa;
    private javax.swing.JTextField jTextFieldCodUnidade;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldFiltroUnidade;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldVencimento;
    // End of variables declaration//GEN-END:variables
}
