/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DaoDespesa;
import Model.Despesa;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        CarregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jPanelFiltros = new javax.swing.JPanel();
        jPanelFiltroUnidade = new javax.swing.JPanel();
        jLabelFiltroUnidade = new javax.swing.JLabel();
        jTextFieldFiltroUnidade = new javax.swing.JTextField();
        jButtonFiltrarUnidade = new javax.swing.JButton();
        jButtonFitroDespesasVencidas = new javax.swing.JButton();
        jButtonLimparFiltros = new javax.swing.JButton();
        jPanelResumo = new javax.swing.JPanel();
        jLabelTotalInquilinoInfo = new javax.swing.JLabel();
        jLabelTotalUnidadeInfo = new javax.swing.JLabel();
        jLabelTotalInquilinoDado = new javax.swing.JLabel();
        jLabelTotalUnidadesDado = new javax.swing.JLabel();
        jPanelResumo1 = new javax.swing.JPanel();
        jLabelDespesaAtivaInfo = new javax.swing.JLabel();
        jLabelTotalDespesasVencidasInfo = new javax.swing.JLabel();
        jLabelDespesasAtivasDado = new javax.swing.JLabel();
        jLabelTotalDespesasVencidasDado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Despesas = new javax.swing.JButton();
        jButtonInquilinos = new javax.swing.JButton();
        jButtonUnidades = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTelaPrincipal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle"));

        jPanelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jPanelFiltroUnidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar por Unidade"));

        jLabelFiltroUnidade.setText("Unidade");

        jTextFieldFiltroUnidade.setText("1");

        jButtonFiltrarUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/filtro.png"))); // NOI18N
        jButtonFiltrarUnidade.setText("Filtrar");
        jButtonFiltrarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarUnidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltroUnidadeLayout = new javax.swing.GroupLayout(jPanelFiltroUnidade);
        jPanelFiltroUnidade.setLayout(jPanelFiltroUnidadeLayout);
        jPanelFiltroUnidadeLayout.setHorizontalGroup(
            jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                .addGroup(jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                        .addComponent(jLabelFiltroUnidade)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jTextFieldFiltroUnidade))
                .addGap(18, 18, 18)
                .addComponent(jButtonFiltrarUnidade)
                .addContainerGap())
        );
        jPanelFiltroUnidadeLayout.setVerticalGroup(
            jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelFiltroUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFiltrarUnidade)
                    .addGroup(jPanelFiltroUnidadeLayout.createSequentialGroup()
                        .addComponent(jLabelFiltroUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFiltroUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFitroDespesasVencidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Despesas.png"))); // NOI18N
        jButtonFitroDespesasVencidas.setText("Despesas Vencidas");
        jButtonFitroDespesasVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFitroDespesasVencidasActionPerformed(evt);
            }
        });

        jButtonLimparFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limparFiltro.png"))); // NOI18N
        jButtonLimparFiltros.setText("Limpar Filtros");
        jButtonLimparFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFiltroUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFitroDespesasVencidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimparFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addComponent(jPanelFiltroUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFitroDespesasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLimparFiltros)
                .addContainerGap())
        );

        jPanelResumo.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo Unidades / Inquilinos"));

        jLabelTotalInquilinoInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalInquilinoInfo.setText("Total Inquilinos");

        jLabelTotalUnidadeInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalUnidadeInfo.setText("Total Unidades");

        jLabelTotalInquilinoDado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalInquilinoDado.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTotalInquilinoDado.setText("10000");

        jLabelTotalUnidadesDado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalUnidadesDado.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTotalUnidadesDado.setText("10000");

        javax.swing.GroupLayout jPanelResumoLayout = new javax.swing.GroupLayout(jPanelResumo);
        jPanelResumo.setLayout(jPanelResumoLayout);
        jPanelResumoLayout.setHorizontalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResumoLayout.createSequentialGroup()
                        .addComponent(jLabelTotalUnidadeInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotalUnidadesDado))
                    .addGroup(jPanelResumoLayout.createSequentialGroup()
                        .addComponent(jLabelTotalInquilinoInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jLabelTotalInquilinoDado)))
                .addContainerGap())
        );
        jPanelResumoLayout.setVerticalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalInquilinoInfo)
                    .addComponent(jLabelTotalInquilinoDado))
                .addGap(18, 18, 18)
                .addGroup(jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalUnidadeInfo)
                    .addComponent(jLabelTotalUnidadesDado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelResumo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo Despesas"));

        jLabelDespesaAtivaInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDespesaAtivaInfo.setText("Total Despesas Ativas");

        jLabelTotalDespesasVencidasInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalDespesasVencidasInfo.setText("Total Despesas Vencidas");

        jLabelDespesasAtivasDado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDespesasAtivasDado.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDespesasAtivasDado.setText("10000");

        jLabelTotalDespesasVencidasDado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalDespesasVencidasDado.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTotalDespesasVencidasDado.setText("10000");

        javax.swing.GroupLayout jPanelResumo1Layout = new javax.swing.GroupLayout(jPanelResumo1);
        jPanelResumo1.setLayout(jPanelResumo1Layout);
        jPanelResumo1Layout.setHorizontalGroup(
            jPanelResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDespesaAtivaInfo)
                    .addComponent(jLabelTotalDespesasVencidasInfo))
                .addGap(45, 45, 45)
                .addGroup(jPanelResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalDespesasVencidasDado)
                    .addComponent(jLabelDespesasAtivasDado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelResumo1Layout.setVerticalGroup(
            jPanelResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDespesaAtivaInfo)
                    .addComponent(jLabelDespesasAtivasDado))
                .addGap(18, 18, 18)
                .addGroup(jPanelResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalDespesasVencidasDado)
                    .addComponent(jLabelTotalDespesasVencidasInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        Despesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Despesas.png"))); // NOI18N
        Despesas.setText("Despesas");
        Despesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespesasActionPerformed(evt);
            }
        });

        jButtonInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/inquilino.png"))); // NOI18N
        jButtonInquilinos.setText("Inquilinos");
        jButtonInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInquilinosActionPerformed(evt);
            }
        });

        jButtonUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/unidade.png"))); // NOI18N
        jButtonUnidades.setText("Unidades");
        jButtonUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Despesas)
                    .addComponent(jButtonInquilinos)
                    .addComponent(jButtonUnidades))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Despesas)
                .addGap(18, 18, 18)
                .addComponent(jButtonInquilinos)
                .addGap(18, 18, 18)
                .addComponent(jButtonUnidades)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResumo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelResumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jPanelResumo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelResumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );

        jTableTelaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Despesa", "Cod Unidade", "Descrição", "Tipo", "Valor", "Vencimento", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableTelaPrincipal);

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFiltrarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarUnidadeActionPerformed

        CarregarTabelaFiltroUnidade();
    }//GEN-LAST:event_jButtonFiltrarUnidadeActionPerformed

    private void jButtonFitroDespesasVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFitroDespesasVencidasActionPerformed

        CarregarTabelaFiltroDespesaVencida();
    }//GEN-LAST:event_jButtonFitroDespesasVencidasActionPerformed

    private void jButtonLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparFiltrosActionPerformed

        CarregarTabela();
    }//GEN-LAST:event_jButtonLimparFiltrosActionPerformed

    private void DespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespesasActionPerformed

        try {
            TelaDespesa telaDespesas = new TelaDespesa();
            telaDespesas.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }         
        finally{
        dispose();
        }          
    }//GEN-LAST:event_DespesasActionPerformed

    private void jButtonInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInquilinosActionPerformed

        try {
            TelaInquilino telaInquilino = new TelaInquilino();
            telaInquilino.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }         
        finally{
        dispose();
        }          
    }//GEN-LAST:event_jButtonInquilinosActionPerformed

    private void jButtonUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnidadesActionPerformed

        try {
            TelaUnidade telaUnidades = new TelaUnidade();
            telaUnidades.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }         
        finally{
        dispose();
        }          
        
    }//GEN-LAST:event_jButtonUnidadesActionPerformed

        private void CarregarTabelaFiltroDespesaVencida(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableTelaPrincipal.getModel();
        tabela.setNumRows(0);
      
        DaoDespesa daoDespesas = new DaoDespesa();
        
        try {
            for(Despesa d: daoDespesas.listarDespesaVencidada()){
                tabela.addRow(new Object[]{
                    d.getCodDespesa(),
                    d.getCodUnidade(),                   
                    d.getDescricao(),
                    d.getTipo(),
                    d.getValor(),
                    d.getVencimento(),
                    d.getStatusPgto()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }
    
    private void CarregarTabela(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableTelaPrincipal.getModel();
        tabela.setNumRows(0);
      
        DaoDespesa daoDespesas = new DaoDespesa();
        
        try {
            for(Despesa d: daoDespesas.listarDespesa()){
                tabela.addRow(new Object[]{
                    d.getCodDespesa(),
                    d.getCodUnidade(),                   
                    d.getDescricao(),
                    d.getTipo(),
                    d.getValor(),
                    d.getVencimento(),
                    d.getStatusPgto()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }        
    
    private void CarregarTabelaFiltroUnidade(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableTelaPrincipal.getModel();
        tabela.setNumRows(0);
      
        DaoDespesa daoDespesas = new DaoDespesa();
        
        try {
            for(Despesa d: daoDespesas.listarDespesaFiltroUnidade(Integer.parseInt(jTextFieldFiltroUnidade.getText()))){
                tabela.addRow(new Object[]{
                    d.getCodDespesa(),
                    d.getCodUnidade(),                   
                    d.getDescricao(),
                    d.getTipo(),
                    d.getValor(),
                    d.getVencimento(),
                    d.getStatusPgto()
                });
            }                            
        } catch (Exception erro) {            
            JOptionPane.showMessageDialog(null,"Erro ao Carregar tabela",
                    "Erro",JOptionPane.ERROR_MESSAGE); 
        }  
    }  
    
      
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Despesas;
    private javax.swing.JButton jButtonFiltrarUnidade;
    private javax.swing.JButton jButtonFitroDespesasVencidas;
    private javax.swing.JButton jButtonInquilinos;
    private javax.swing.JButton jButtonLimparFiltros;
    private javax.swing.JButton jButtonUnidades;
    private javax.swing.JLabel jLabelDespesaAtivaInfo;
    private javax.swing.JLabel jLabelDespesasAtivasDado;
    private javax.swing.JLabel jLabelFiltroUnidade;
    private javax.swing.JLabel jLabelTotalDespesasVencidasDado;
    private javax.swing.JLabel jLabelTotalDespesasVencidasInfo;
    private javax.swing.JLabel jLabelTotalInquilinoDado;
    private javax.swing.JLabel jLabelTotalInquilinoInfo;
    private javax.swing.JLabel jLabelTotalUnidadeInfo;
    private javax.swing.JLabel jLabelTotalUnidadesDado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelFiltroUnidade;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JPanel jPanelResumo;
    private javax.swing.JPanel jPanelResumo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTelaPrincipal;
    private javax.swing.JTextField jTextFieldFiltroUnidade;
    // End of variables declaration//GEN-END:variables
}
